version: 2.1
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
          GOPROXY: https://gocenter.io
    working_directory: /go/src/github.com/waynz0r/grafterm
    steps:
      - checkout
      - run: make ci

  release:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
          GOPROXY: https://gocenter.io
    working_directory: /go/src/github.com/waynz0r/grafterm
    steps:
      - checkout
      - run: make ci-release
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./bin/

workflows:
  version: 2
  main:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
